version: '3'

services:
  web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      ports:
          - 8000:8000
    # build: 
    # command: pyton3 manage.py runserver 127.0.0.1:8000
    # volumes:
    #   - .:/app
    # ports:
    #   - "8000:8000"
