# Generated by Django 3.1.7 on 2021-03-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_auto_20210310_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restapp.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='8RCJVM94', max_length=10),
        ),
    ]
