# Generated by Django 3.1.7 on 2021-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20210316_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='7M365VZB', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('details', 'timestamp')},
        ),
    ]
