# Generated by Django 3.1.7 on 2021-03-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_auto_20210316_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='details',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='JW4KQDFZ', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order', 'timestamp')},
        ),
    ]
