# Generated by Django 3.1.7 on 2021-03-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_auto_20210316_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='DK1KWWB8', max_length=10),
        ),
    ]
