# Generated by Django 3.1.7 on 2021-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_auto_20210316_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='3ASRTCSO', max_length=10),
        ),
    ]
