# Generated by Django 3.1.7 on 2021-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0010_auto_20210316_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='5RSEYPKY', max_length=10),
        ),
    ]
