# Generated by Django 3.1.7 on 2021-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0011_auto_20210316_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='B2L0G9YG', max_length=10),
        ),
    ]
