# Generated by Django 3.1.7 on 2021-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0014_auto_20210316_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='WUOGDQ9R', max_length=10),
        ),
    ]
