# Generated by Django 3.1.7 on 2021-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0015_auto_20210317_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='Y4JHFCN0', max_length=10),
        ),
    ]
