# Generated by Django 3.1.7 on 2021-03-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0017_auto_20210317_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='OFVJU02V', max_length=10),
        ),
    ]
