# Generated by Django 3.1.7 on 2021-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0018_auto_20210317_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='4AZ88EIX', max_length=10),
        ),
    ]
