# Generated by Django 3.1.7 on 2021-03-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0019_auto_20210317_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='F7ESNETC', max_length=10),
        ),
    ]
