# Generated by Django 3.1.7 on 2021-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0020_auto_20210317_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='VDE7QUFD', max_length=10),
        ),
    ]
