# Generated by Django 3.1.7 on 2021-03-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0023_auto_20210320_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='8J0WJMHE', max_length=10),
        ),
    ]
